events { }

http {
    include       /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html =404;
        }

        
        resolver 127.0.0.11 valid=30s;

        location /api/products {
            set $target http://catalog-services:3002;
            proxy_pass $target;
        }

        location /api/cart {
            set $target http://cart-services:3003;
            proxy_pass $target;
        }

        location /api/orders {
            set $target http://order-services:3004;
            proxy_pass $target;
        }

        location /api/payments {
            set $target http://payment-service:3005;
            proxy_pass $target;
        }

        location /api/users {
            set $target http://user-service:3001;
            proxy_pass $target;
        }
    }
}