# =============================================================================
# User Service — Build & Deploy to AWS EKS (GitOps Version)
# =============================================================================
name: "Backend: Deploy User Service"

on:
  push:
    branches: ["main"]
    paths:
      - "web-app/ecommerce-microservices/services/user-service/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::644981759771:role/GitHubActionRole
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.registry }}
          ECR_REPOSITORY: prod-user-service
          IMAGE_TAG: v${{ github.run_number }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./web-app/ecommerce-microservices/services/user-service
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update GitOps Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git clone https://${{ secrets.GITOPS_TOKEN }}@github.com/amr-elzoghby/web-app-gitops.git gitops-repo
          cd gitops-repo
          
          TARGET_FILE="apps/user-service/deployment.yaml"
          ECR_IMAGE="${{ steps.login-ecr.registry }}/prod-user-service"
          NEW_TAG="v${{ github.run_number }}"
          
          sed -i "s|image: .*|image: $ECR_IMAGE:$NEW_TAG|g" $TARGET_FILE
          
          if [ -n "$(git status --porcelain)" ]; then
            git add $TARGET_FILE
            git commit -m "chore(user): deploy $NEW_TAG to EKS [skip ci]"
            git push
          fi
